apiVersion: v1
kind: Service
metadata:
  labels:
    service: api-feed
  name: api-feed
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    service: api-feed
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
