apiVersion: v1
kind: Service
metadata:
  labels:
    service: api-user
  name: api-user
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    service: api-user
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
