apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverse-proxy
  name: reverse-proxy
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    service: reverse-proxy
  type: LoadBalancer
